setup/urls.py
from django.contrib import admin
from django.urls import path,include
from estoque import views as v
from cliente import views as c
from servico import views as s
from transacao import views as t
from cliente.views import ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView
from estoque.views import ProdutoList, ProdutoCreateView, CategoriaCreateView       
from transacao.views import orcamento,TransacaoListView,transacao_detail, TransacaoDeleteView, FornecedorCreateView, FornecedorListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('estoque/', v.ProdutoList.as_view(), name="home_estoque"),
    path ('estoque/cadastro', v.ProdutoCreateView.as_view(), name="cadastrar_produto"),
    path('atualiza_produto/<int:pk>', v.ProductUpdateView.as_view(), name="atualiza_produto"),
    path('delete/<int:pk>',v.ProductDeleteView.as_view(), name="delete_produto"),
    path ('estoque/cadastro_categoria', v.CategoriaCreateView.as_view(), name="cadastro_categoria"),
    path ('estoque/listar_categoria', v.CategoriaListView.as_view(), name="listar_categoria"),
    path('', v.home, name="home"),

    #URLS dos clientes
    path('cliente/', c.ClientListView.as_view(), name="clientes"),
    path ('cadastrar_cliente', c.ClientCreateView.as_view(), name="cadastrar_cliente"),
    path('atualiza_cliente/<int:pk>', c.ClientUpdateView.as_view(), name="atualiza_cliente"),
    path('delete_cliente/<int:pk>', c.ClientDeleteView.as_view(), name="delete_cliente"),

    #URLS dos serviços
      path('servico/', s.ordem_servico_list, name='home_servicos'),  # noqa E501
      path('servico/cadastrar_ordemservico', s.OrdenServicoCreateView.as_view(), name='ordem_servico_create'),  # criacao do serviço
      path('visualizar_os/<int:pk>', s.ordem_servico_detail, name="visualizar_os"),
      path('servico/criar', s.ServicoCreateView.as_view(), name="cadastrar_servico"),

    #URLS ORÇAMENTO
    path('orcamento/<int:id>/', t.orcamento, name='orcamento'),
    path('transacao/listar_orcamentos/', t.TransacaoListView.as_view(), name='listar_orcamento'),
    path('trasancao/<int:id>/', t.transacao_detail, name='visualizar_orcamento'),
    path('delete_orcamento/<int:pk>', t.TransacaoDeleteView.as_view(), name="delete_orcamento"),

    #URL FORNECEDOR
    path('cadastro_fornecedor', t.FornecedorCreateView.as_view(), name='cadastrar_fornecedor'),
    path('visualizar_fornecedor', t.FornecedorListView.as_view(), name='listar_fornecedor'),
]

servico/models.py
from django.db import models
from cliente.models import Cliente
from estoque.models import Product

# Create your models here.
class Servico(models.Model):
    servico = models.CharField(verbose_name="Serviço", max_length=150, null=False, blank=False)
    
    #responsavel para mostrar o nome correto no retorno
    def __str__(self):
        return self.servico
    
SITUACAO = (
    ('pe', 'Pendente'),
    ('ca', 'Cancelado'),
    ('an', 'Andamento'),
    ('ap', 'Aprovado'),
)



class OrdemServico(models.Model):
    situacao = models.CharField('Situação', max_length=2, choices=SITUACAO)
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,
        verbose_name='cliente',
        related_name='clientes',
        null=True,
        blank=True
    )
    servico = models.ForeignKey(Servico, 
        on_delete=models.CASCADE,
        null=True,
        blank=True
        )
    produto = models.ForeignKey(Product, 
        on_delete=models.CASCADE,
        null=True,
        blank=True
        )
    #quantidade = models.PositiveIntegerField(verbose_name="quantidade", null=True, blank=True)
    #valor_produto = models.DecimalField('valor Produto', max_digits=10,
    #decimal_places=2, blank=True, default=0)
    valor_custo = models.DecimalField('Valor Custo', max_digits=8, decimal_places=2, null=True, blank=True)
    valor_lucro = models.DecimalField('Valor Lucro', max_digits=8, decimal_places=2, null=True, blank=True)
    data = models.DateField('Data do Serviço', null=True, blank=True)
    observacao = models.TextField('Observacção', null=True, blank=True)
    valor = models.DecimalField('Valor total', max_digits=10,
    decimal_places=2, blank=True, default=0)
    
    def __str__(self):
        return self.servico.servico

    
    #calculo
    def save(self, *args, **kwargs):
    	self.valor_lucro = self.valor - self.valor_custo 
    	self.produto.valor_venda += self.valor_custo
    	self.produto.save()
    	return super(OrdemServico, self).save(*args, **kwargs)
    

       #calculo
   # def save(self, *args, **kwargs):
    #	self.subtotal = self.preco * self.quantidade 
    #	self.compra.valor_compra += self.subtotal
    #	self.compra.save()
    #	return super(Produto, self).save(*args, **kwargs)

    

    


     
    

servico/forms.py
from django import forms

from .models import OrdemServico


class OrdemServicoForm(forms.ModelForm):
    servico = forms.CharField()
    valor = forms.DecimalField()
    proxima_visita = forms.DateField(
        label='Próxima Visita',
        required=False,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'form-control'
            }),
        input_formats=('%Y-%m-%d',),
    )

    class Meta:
        model = OrdemServico
        fields = ('situacao',)

servico/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

#from .forms import OrdemServicoForm
from .models import OrdemServico, Servico


def ordem_servico_list(request):
    template_name = 'servico/ordem_servico_list.html'
    object_list = OrdemServico.objects.all()

    search = request.GET.get('search')
    if search:
        object_list = object_list.filter(situacao=search)

    context = {'object_list': object_list}
    return render(request, template_name, context)


class OrdenServicoCreateView(CreateView):
    model = OrdemServico
    fields = ["servico","cliente","situacao","produto","data","observacao","valor_custo","valor"]
    success_url = reverse_lazy("home")

    



def ordem_servico_detail(request, pk):
    template_name = 'servico/ordem_servico_detail.html'
    instance = OrdemServico.objects.get(pk=pk)
    context = {'object': instance}
    return render(request, template_name, context)


class ServicoCreateView(CreateView):
    model = Servico
    fields = ["servico"]
    success_url = reverse_lazy("home")

templates/servico/ordem_servico_detail.html
<!-- ordem_servico_detail.html -->
{% extends "base.html" %}

{% block conteudo %}
<br><br>
<div class="container">
  <img src="/static/img/check-box_6399627.png" height="50" width="50">
  <h4>OS Nº: {{ object.pk }}</h4>

  <h5>Cliente: {{ object.cliente }} </h5><B>Data: {{ object.data|date:"d/m/Y" }}</B>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th>Valor</th>
        
      </tr>
    </thead>
    <tbody>
    
        <tr>
          <td><b>Serviço: </b> {{ object.servico.servico }}</td>
          <td> </td>
          <td><b>Custo: </b>R$: {{ object.valor_custo }}</td>
        </tr>
      
        <TR>
          <td>
            <b>Produto utilizado: </b> {{object.produto}}
          </td>
          <td>
            
          </td>
          <td>
            <b>Cobrado: </b>R$: {{ object.valor }} 
           </td>
        </TR>
        
    <tr>
     
      <td>
       <b> Observação: </b>{{object.observacao}}
      </td>
      <td>
       </td>
       <td>
        <b>LUCROU : </b>{{object.valor_lucro}}
       </td>
    </tr>
   
    </tbody>
  </table>
</div>
{% endblock conteudo %}

templates/servico/ordem_servico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}




{% block conteudo %}
<form method="POST">
  {% csrf_token %}
  {{ form | crispy}}
  <button type="submit" class="btn btn-primary">Salvar</button>
</form>
{% endblock conteudo %}

templates/servico/ordem_servico_list.html
<!-- ordem_servico_list.html -->
{% extends "base.html" %}

{% block conteudo %}
<div class="container">
  <h1>Ordens de Serviço</h1>

  <a
    href="{% url 'ordem_servico_create' %}"
    class="btn btn-primary"
  >Adicionar</a>

  <div class="row mt-3">
    <div class="col-sm-2">
      <h3>Situação</h3>
      <div class="list-group">
        <a
          href="{% url 'home_servicos' %}"
          class="list-group-item list-group-item-action"
        >
          Limpar filtro
        </a>
        <a
          href="{% url 'home_servicos' %}?search=pe"
          class="list-group-item list-group-item-action"
        >
          Pendente
        </a>
        <a
          href="{% url 'home_servicos' %}?search=ca"
          class="list-group-item list-group-item-action"
        >
          Cancelado
        </a>
        <a
          href="{% url 'home_servicos' %}?search=an"
          class="list-group-item list-group-item-action"
        >
          Andamento
        </a>
        <a
          href="{% url 'home_servicos' %}?search=ap"
          class="list-group-item list-group-item-action"
        >
          Aprovado
        </a>
      </div>

    </div>
    <div class="col-sm-10">
      <table class="table table-dark">
        <thead>
          <tr>
            <th>Num</th>
            <th>Cliente</th>
            <th>Situação</th>
            <th>Serviço</th>
            <th>Valor</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.pk }}</td>
              <td>
               {{ object.cliente.nome }}
              </td>
              <td>{{ object.get_situacao_display }}</td>
              <td>{{ object.servico.servico }}</td>
              <td>R$: {{ object.valor }}</td>
              
              <td>
               <a href="{% url 'visualizar_os' pk=object.pk %}" class="btn btn-light btn-sm">Visualizar</a>
             </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock conteudo %}

templates/servico/ordemservico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}




{% block conteudo %}
<div class="container">
    <br>
    <br>
<h4>Cadastrar OS SERVIÇO</h4>
  
    <form method="POST">
            {% csrf_token %}
            {{ form | crispy}}
            <button type="submit" class="btn btn-primary">SALVAR</button>
        </form>
</div>
<br>
<br>
{% endblock conteudo %}

templates/servico/servico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}




{% block conteudo %}
<div class="container">
    <br>
    <h4>Cadastrar serviço</h4>
    <form method="POST">
      {% csrf_token %}
      {{ form | crispy}}
      <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>
{% endblock conteudo %}