setup/urls.py
from django.contrib import admin
from django.urls import path,include
from estoque import views as v
from cliente import views as c
from servico import views as s
from transacao import views as t
from cliente.views import ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView
from estoque.views import ProdutoList, ProdutoCreateView, CategoriaCreateView       
from transacao.views import orcamento,TransacaoListView,transacao_detail, TransacaoDeleteView, FornecedorCreateView, FornecedorListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('estoque/', v.ProdutoList.as_view(), name="home_estoque"),
    path ('estoque/cadastro', v.ProdutoCreateView.as_view(), name="cadastrar_produto"),
    path('atualiza_produto/<int:pk>', v.ProductUpdateView.as_view(), name="atualiza_produto"),
    path('delete/<int:pk>',v.ProductDeleteView.as_view(), name="delete_produto"),
    path ('estoque/cadastro_categoria', v.CategoriaCreateView.as_view(), name="cadastro_categoria"),
    path ('estoque/listar_categoria', v.CategoriaListView.as_view(), name="listar_categoria"),
    path('', v.home, name="home"),

    #URLS dos clientes
    path('cliente/', c.ClientListView.as_view(), name="clientes"),
    path ('cadastrar_cliente', c.ClientCreateView.as_view(), name="cadastrar_cliente"),
    path('atualiza_cliente/<int:pk>', c.ClientUpdateView.as_view(), name="atualiza_cliente"),
    path('delete_cliente/<int:pk>', c.ClientDeleteView.as_view(), name="delete_cliente"),

    #URLS dos serviços
      path('servico/', s.ordem_servico_list, name='home_servicos'),  # noqa E501
      path('servico/cadastrar_ordemservico', s.OrdenServicoCreateView.as_view(), name='ordem_servico_create'),  # criacao do serviço
      path('visualizar_os/<int:pk>', s.ordem_servico_detail, name="visualizar_os"),
      path('servico/criar', s.ServicoCreateView.as_view(), name="cadastrar_servico"),

    #URLS ORÇAMENTO
    path('orcamento/<int:id>/', t.orcamento, name='orcamento'),
    path('transacao/listar_orcamentos/', t.TransacaoListView.as_view(), name='listar_orcamento'),
    path('trasancao/<int:id>/', t.transacao_detail, name='visualizar_orcamento'),
    path('delete_orcamento/<int:pk>', t.TransacaoDeleteView.as_view(), name="delete_orcamento"),

    #URL FORNECEDOR
    path('cadastro_fornecedor', t.FornecedorCreateView.as_view(), name='cadastrar_fornecedor'),
    path('visualizar_fornecedor', t.FornecedorListView.as_view(), name='listar_fornecedor'),
]

transacao/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.safestring import mark_safe

class Fornecedor(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = u'Fornecedor'
        verbose_name_plural = u'FORNECEDOR'
        


class Material(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = u'Material'
        verbose_name_plural = u'MATERIAL'

class Compra(models.Model):
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE)
    nota_fiscal = models.CharField(max_length=10)
    data = models.DateField()
    valor_compra = models.DecimalField(max_digits=10,
    decimal_places=2, blank=True, default=0)

    def imprimir(self):
            return mark_safe("""<a href=\"/orcamento/%s/\" target="_blank"><img src=\"/static/images/b_print.png\"></a>""" % self.id)

    class Meta:
        verbose_name = u'Compra'
        verbose_name_plural = u'COMPRAS'
        ordering = ['-data']

class Produto(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    preco = models.DecimalField(u'PREÇO',max_digits=15,decimal_places=2)
    quantidade = models.DecimalField(u'QUANTIDADE', max_digits=5,decimal_places=0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2,
    editable=False)
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)

    def __str__(self):
        return self.material.nome + ",R$" + str(self.preco) +"," + str(self.quantidade) + ",R$" + str(self.subtotal)

    class Meta:
        verbose_name = u'Produto'
        verbose_name_plural = u'PRODUTOS'


    #calculo
    def save(self, *args, **kwargs):
    	 self.subtotal = self.preco * self.quantidade 
    	 self.compra.valor_compra += self.subtotal
    	 self.compra.save()
    	 return super(Produto, self).save(*args, **kwargs)

transacao/views.py
# -*- Mode: Python; coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, TemplateView
from .models import Fornecedor, Compra, Produto, Material



@login_required(redirect_field_name='redirect_to')
def orcamento(request, id=None, *args, **kwargs):
	contexto = {}
	contexto['orcamento'] = Compra.objects.get(id=id)

	return render(request, "orcamento.html", contexto)


#class  base de views utilizando a class Clients
class TransacaoListView(ListView):
    model = Compra
    template_name = 'transacao_list.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def transacao_detail(request, pk):
    template_name = 'transacao/orcamento_detail.html'
    instance = Compra.objects.get(pk=pk)
    context = {'object': instance}
    return render(request, template_name, context)

templates/transacao/compra_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block conteudo %}
<main class="container">
  <br>
 
  
  <div class="alert alert-danger" role="alert">
    <h4>Deletar o orçamento</h4>
  </div>
  <tr>
      <td></td>
    <td>{{ compra.valor_compra }}</td>

<P><b>Deseja realmente excluir o orcamento com os dados abaixo ?</b></P>
<p>Nome do cliente: {{ compra.fornecedor.nome }}</p>
<p>NOTA FISCAL: {{ compra.nota_fiscal}}</p>

<p>DATA: {{ compra.data }}</p>

<table class="table table-striped table-bordered table-hover  text-center">
  <thead class="btn-primary print">
    <tr>
      <th>#ID</th>
      <th class="text-center">PRODUTO</th>
      <th>VALOR UNITÁRIO</th>
      <th>QUANTIDADE</th>
    </tr>
  </thead>
  <tbody>
   {% for item_do_orcamento in compra.produto_set.all %}
    <tr>
      <td>{{ item_do_orcamento.id }}</td>
      <td class="text-center">{{ item_do_orcamento.material }}</td>
      <td>{{ item_do_orcamento.preco }}</td>
      <td>{{ item_do_orcamento.quantidade }}</td>
    </tr>
     {% endfor %}
  </tbody>
</table>
<form method="POST">
    {% csrf_token %}
  <button type="submit" class="btn btn-danger">Confirmar exclusão</button>
  <a href="{% url 'clientes' %}" class="btn btn-primary">Cancelar</a>
</form>
<br>
</main>
{% endblock %}

templates/transacao/compra_list.html
{% extends 'base.html' %}
{% block conteudo %}

<main class="container">
 
    <h2>ORÇAMENTOS</h2>
    <a href="/admin/transacao/compra/add/" target="_blank" class="btn btn-primary btn-sm"> CRIAR ORÇAMENTO</a> Somente pelo admin
    <br><br>
  <form method="GET">
    <div class="input-group">
      <input type="search" name ="buscar" class="form-control rounded" id ="text" placeholder="Buscar pelo numero do orçamento ou nome cliente" aria-label="Search"
        aria-describedby="search-addon"/>
      <button type="submit" class="btn btn-outline-primary">Pesquisar</button>
    </div>
  </form>
  <br>
    <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Nota Fiscal</th>
            <th scope="col">Data</th>
            <th scope="col">Valor Total</th>
            <th scope="col">Ações</th>
        </thead>
        <tbody>
        
            {% for compra in compra_list %}
            
            <tr>
              <th scope="row">{{ compra.pk }}</th>
                <td> {{ compra.fornecedor.nome }}</td>
              <td> {{ compra.nota_fiscal}}</td>
                <td>{{ compra.data }}</td>
              <td>{{ compra.valor_compra }}</td>
              <td>
                 <a href="/orcamento/{{ compra.pk }}" target="_blank" class="btn btn-light btn-sm"> Imprímir</a>
                 <a href="{% url 'delete_orcamento' pk=compra.pk %}" class="btn btn-danger btn-sm">Excluír</a>
              </td>
            </tr>
            {% endfor %}
         
        
        </tbody>
      </table>
   
</main>
<br>
<br>

{% endblock %}

templates/transacao/fornecedor_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block conteudo %}
<main class="container">
  <br>
 
  {% if fornecedor.pk  %}
<h1>Editar fornecedor</h1>


{% else %}
<h4>Cadastrar fornecedor</h4>
{%endif%}



<form method="POST">
  {% csrf_token %}
  {{ form | crispy}}
  <button type="submit" class="btn btn-primary">Salvar</button>
</form>
<br>
</main>
{% endblock %}






  

templates/transacao/fornecedor_list.html
{% extends 'base.html' %}
{% block conteudo %}

<main class="container">
 
    <h2>Fornecedor</h2>
    <br><br>
  <form method="GET">
    <div class="input-group">
      <input type="search" name ="buscar" class="form-control rounded" id ="text" placeholder="Buscar pelo numero do orçamento ou nome cliente" aria-label="Search"
        aria-describedby="search-addon"/>
      <button type="submit" class="btn btn-outline-primary">Pesquisar</button>
    </div>
  </form>
  <br>
    <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Ações</th>
        </thead>
        <tbody>
        
            {% for fornecedor in fornecedor_list %}
            
            <tr>
              <th scope="row">{{ fornecedor.pk }}</th>
                <td> {{ fornecedor.nome }}</td>
             
              <td>
                 <a href="/orcamento/{{ compra.pk }}" target="_blank" class="btn btn-light btn-sm"> Imprímir</a>
                 <a href="{ url 'delete_orcamento' pk=compra.pk %}" class="btn btn-danger btn-sm">Excluír</a>
              </td>
            </tr>
            {% endfor %}
         
        
        </tbody>
      </table>
   
</main>
<br>
<br>

{% endblock %}